In [5]:
import numpy as np

#Matrix Multiplication

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A)
print(B)
A@B

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [6]:
#Element-wise Multiplication

result=A*B
print(result)

[[ 5 12]
 [21 32]]


In [7]:
#Transpose(swap rows and columns)

transposed=A.T
transposed=np.transpose(A)
print(transposed)
print(A)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [8]:
det=np.linalg.det(A)
print(det)

-2.0000000000000004


In [ ]:
#Matrix Inverse

inverse=np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Matrix Rank

C=np.array([[1,2,3],[4,5,6]])
rank=np.linalg.matrix_rank(C)
print(rank)
print(C)

2
[[1 2 3]
 [4 5 6]]


In [ ]:
eigenvectors=np.linalg.eig(A)
print(eigenvectors)


EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
#Solving linear systems

solution=np.linalg.solve(A,B)
print(solution)

[[-3. -4.]
 [ 4.  5.]]


In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[4,5,6],[7,8,9],[0,1,2]])
print(A)
print(B)
A@B

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [0 1 2]]


array([[ 18,  24,  30],
       [ 51,  66,  81],
       [ 84, 108, 132]])

In [ ]:
result=A*B
print(result)

[[ 4 10 18]
 [28 40 54]
 [ 0  8 18]]


In [ ]:
transposed=A.T
transposed=np.transpose(A)
print(transposed)
print(A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
det=np.linalg.det(B)
print(det)

0.0


In [ ]:
Z=[[1, 2, 3],
   [4, 5, 6],
   [7, 8, 10]]
inverse=np.linalg.inv(Z)
print(inverse)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [ ]:
rank=np.linalg.matrix_rank(Z)
print(rank)

3


In [ ]:
eigenvectors=np.linalg.eig(A)
print(eigenvectors)


EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [ ]:
Y=[[1, 9, 10],
   [4, 5, 6],
   [7, 8, 10]]
solution=np.linalg.solve(Y,Z)
print(solution)

[[ 1.   1.4  1.4]
 [ 0.   2.4  1.4]
 [-0.  -2.1 -1.1]]
