In [3]:
import numpy as np

#Crop yields for 4 farme in 5 seasons (in tons)
crop_yields=np.array([
    [12.5,  13.2,  14.1,  13.8,  15.2],  #Farm 1-North Region
    [10.3,  11.5,  10.8,  12.1,  11.9],  #Farm 2-South Region
    [15.1,  14.8,  16.2,  15.5,  16.8],  #Farm 3-East Region
    [11.2,  10.9,  12.3,  11.7,  12.8]   #Farm 4-West Region
])
print('Crop Yields Array(tons):')
print(crop_yields)
print(f'\nShape:{crop_yields.shape}')
print(f'\nData type:{crop_yields.dtype}')
print(f'\nTotal elements:{crop_yields.size}')
print(f'\nNumber of dimensions:{crop_yields.ndim}')

#AGRICULTURAL ANALYSIS OPERATIONS
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\nTotal Production:{total_yield} tons')
print(f'\nAverage Yield Per Farm:{avg_yield_per_farm} tons')
print(f'\nAverage Yield Per Season:{avg_yield_per_season} tons')
print(f'\nMaximum Yield:{max_yield} tons')
print(f'\nMinimum Yield:{min_yield} tons')

#Find best performing farm
best_farm=np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm:Farm{best_farm+1}')
print(f'\nTheir average yield:{avg_yield_per_farm[best_farm]:.2f} tons')


Crop Yields Array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape:(4, 5)

Data type:float64

Total elements:20

Number of dimensions:2

Total Production:262.7 tons

Average Yield Per Farm:[13.76 11.32 15.68 11.78] tons

Average Yield Per Season:[12.275 12.6   13.35  13.275 14.175] tons

Maximum Yield:16.8 tons

Minimum Yield:10.3 tons

Best performing farm:Farm3

Their average yield:15.68 tons


In [18]:
import pandas as pd

df=pd.DataFrame(crop_yields,index=["a","b","c","d"])
print("CROP YIELD IN TABLE FORMAT:")
display(df)

CROP YIELD IN TABLE FORMAT:


,0,1,2,3,4
a,12.5,13.2,14.1,13.8,15.2
b,10.3,11.5,10.8,12.1,11.9
c,15.1,14.8,16.2,15.5,16.8
d,11.2,10.9,12.3,11.7,12.8
