In [ ]:
import numpy as np
#Nutrient requirements for 3 crops(N,P,K in kg/ha)
#Rows:Crops(Wheat,Corn,Rice)
#Columns:Nutrients(Nitrogen,phosphorous,potassium)
nutrient_needs=np.array([
    [120, 60, 80], #Wheat
    [150, 75, 100], #Corn
    [100, 50, 70], #Rice
])
#Available fertilizer composition(percentage of N,P,K)
#Rows:Fertilizer types
#Columns:Nutrient content

fertilizer_composition=np.array([
    [0.20, 0.10, 0.15],
    [0.15, 0.20, 0.10],
    [0.10, 0.15, 0.25]
])
print('Nutrient Requirements(kg/ha):')
print(nutrient_needs)
print('\nFertilizer Composition(%):')
print(fertilizer_composition)

#Matrix transpose example
print('\nTransposed Nutrient Needs(Nutrient*Crops):')
print(nutrient_needs.T)

#Calculate fertilizer amounts(solving system of equations)
#This would normally require optimization,but for demo:
total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\nTotal nutrients needed per crop:{total_nutrients_per_crop}kg/ha')

#Matrix multiplication: calculate total nutrient delivery
#If we apply 100kg of each fertilizer type
fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f'\nNutrients from 100kg each fertilizer:{nutrients_delivered}')

#Calculate determinant(for checking if matrix is invertible)
det=np.linalg.det(fertilizer_composition)
print(f'\nDeterminant of fertilizer matrix:{det:.6f}')

#Identity matrix example(scaling factor)
scaling=np.eye(3)*1.1       #10% increase
enhanced_needs=np.dot(nutrient_needs,scaling)
print('\nEnhanced nutrient needs(10% increase):')
print(enhanced_needs)

Nutrient Requirements(kg/ha):
[[120  60  80]
 [150  75 100]
 [100  50  70]]

Fertilizer Composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

Transposed Nutrient Needs(Nutrient*Crops):
[[120 150 100]
 [ 60  75  50]
 [ 80 100  70]]

Total nutrients needed per crop:[260 325 220]kg/ha

Nutrients from 100kg each fertilizer:[45. 45. 50.]

Determinant of fertilizer matrix:0.004625

Enhanced nutrient needs(10% increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]
